export class Userform {
  Fname:string;
Lname:string;
DOB:Date;
male:string;
Email:String;
Nationality:string;  
Community:String;
Mobile_Number:null;
Res_addr:String;
Premanent_addr:String;
religion:string;
age:String;
Family_name:string;
Family_occup:string;
Family_income:string;
Caste :string;
degree_BE :string;
degree_BTECH:string;
branch_choice1 :string;
branch_choice2 :string;
branch_choice3:string;
previous_medium:string;
 previous_school:string; 
 previous_passing:string; 
 previous_regno:string;
board_state :string;
board_cbse:string; 
board_other:string;
hsc_language:string; 
hsc_language_marks:Number;
hsc_language_maxmark:Number;
hsc_english_marks :Number;
hsc_english_maxmark :Number;
hsc_maths_marks:Number; 
hsc_maths_maxmark:Number;
hsc_chemistry_marks:Number; 
hsc_chemistry_maxmark :Number;
hsc_physics_marks:Number;
 hsc_physics_maxmark:Number; 
hsc_total_marks:Number; 
hsc_total_maxmark:Number;
 hsc_cutoff:Number; 
 hsc_percentage:Number; 
 hsc_culturals:string; 
 hsc_xtra:string;
hostel_yes:string; 
hostel_no:string; 
first_graduvation_yes :string;
first_graduvation_no:string;

}
                                       